/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datos;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tonqu
 */
public class principal extends javax.swing.JFrame {

    Cuentas cuentas = new Cuentas();
    double[] precios, cantidad, total;
    int indice;
    String[] ventas;
    String[] articulos;

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        iniciarDatos();
    }

    private void iniciarDatos() {
        articulos = new String[]{"Lapicero", "Plumon agua", "Hojas", "Goma", "Tijeras", "sacapuntas"};
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(articulos);
        cmbProductos.setModel(modelo);
        precios = new double[]{14.0, 10.0, 30.0, 2.0, 15.50, 3.50};
        ventas = new String[6];
        cantidad = new double[6];
        total = new double[6];
        indice = 0;
        txtPrecio.setText(String.valueOf(precios[0]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        msg2 = new javax.swing.JLabel();
        cmbProductos = new javax.swing.JComboBox<>();
        msg1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnFinal = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        msg2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        msg2.setText("Cantidad:");

        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });

        msg1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        msg1.setText("Producto:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Precio: ");

        txtPrecio.setEditable(false);

        btnFinal.setText("Finalizar");
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msg1)
                            .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msg2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(32, 32, 32)
                                .addComponent(btnFinal)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msg1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(msg2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinal)
                    .addComponent(btnAgregar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int index = 0;
        String retener = cmbProductos.getSelectedItem().toString();
        index = cuentas.buscarNumero(articulos, retener);
        cantidad[index] = cantidad[index] + Double.parseDouble(txtCantidad.getText());
        total[index] = cantidad[index] * Double.parseDouble(txtPrecio.getText());
        JOptionPane.showMessageDialog(null, cantidad[index]);
        JOptionPane.showMessageDialog(null, retener);
        JOptionPane.showMessageDialog(null, total[index]);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        String[] ordenado = cuentas.mayor(articulos, cantidad);
        double importe = cuentas.sumar(total);
        double[] porcentaje = cuentas.porcentajeProducto(total);
        double[] subtotal = cuentas.subtotalProducto(cantidad, precios);
        StringBuilder contexto = new StringBuilder();
        String titulo = "Reporte final";
        contexto.append("<html><body>");
        contexto.append("<h1><u>REPORTE DE VENTAS</u></h1>");
        contexto.append("<hr><h2>Productos del más al menos vendido </h2>");
        contexto.append("<ol>");
        for (int i = 0; i < ordenado.length; i++) {
            contexto.append("<li>").append(ordenado[i]).append("</li>");
        }
        contexto.append("</ol>");
        contexto.append("<hr><h2>Importe total de ventas </h2>");
        contexto.append(importe).append(" $");
        contexto.append("<hr><h2>Porcentaje de venta por producto </h2>");
        contexto.append("<ol>");
        for (int i = 0; i < porcentaje.length; i++) {
            contexto.append("<li>").append(String.format("%.2f", porcentaje[i])).append(" " + ordenado[i]).append("</li>");
        }
        contexto.append("</ol>");
        contexto.append("<hr><h2>Subtotales de venta por producto </h2>");
        contexto.append("<ol>");
        for (int i = 0; i < subtotal.length; i++) {
            contexto.append("<li>").append(String.format("%.2f", subtotal[i])).append(" " + ordenado[i]).append("</li>");
        }
        contexto.append("</ol>");
        contexto.append("<hr><h1><u>FIN DEL REPORTE</u></h1>");
        contexto.append("</body></html>");
        JOptionPane.showMessageDialog(null, contexto, titulo, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnFinalActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        int index = 0;
        String retener = cmbProductos.getSelectedItem().toString();
        index = cuentas.buscarNumero(articulos, retener);
        txtPrecio.setText(String.valueOf(precios[index]));
    }//GEN-LAST:event_cmbProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFinal;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
